# Example Automations for ICP Identity Addon
# These are example automations that demonstrate how to use the ICP Identity sensor

# Example 1: Alert when mnemonic backup is missing
- alias: "ICP Identity - Alert when no mnemonic backup"
  description: "Notify when ICP identity doesn't have a mnemonic backup"
  trigger:
    - platform: state
      entity_id: sensor.icp_identity
      attribute: has_mnemonic
      to: false
  condition:
    - condition: state
      entity_id: sensor.icp_identity
      state: "connected"
  action:
    - service: persistent_notification.create
      data:
        title: "ICP Identity Security Warning"
        message: "Your ICP identity doesn't have a mnemonic backup. Create one for security!"
        notification_id: "icp_no_mnemonic"

# Example 2: Log principal changes
- alias: "ICP Identity - Log principal changes"
  description: "Log whenever the ICP principal ID changes"
  trigger:
    - platform: state
      entity_id: sensor.icp_identity
      attribute: principal
  condition:
    - condition: template
      value_template: "{{ trigger.from_state.attributes.principal != trigger.to_state.attributes.principal }}"
    - condition: template
      value_template: "{{ trigger.to_state.attributes.principal != 'unknown' }}"
  action:
    - service: logbook.log
      data:
        name: "ICP Identity"
        message: >
          Principal changed from {{ trigger.from_state.attributes.principal }} 
          to {{ trigger.to_state.attributes.principal }}

# Example 3: Monitor connection status
- alias: "ICP Identity - Connection status change"
  description: "React to ICP addon connection changes"
  trigger:
    - platform: state
      entity_id: sensor.icp_identity
      from: "connected"
      to: "disconnected"
    - platform: state
      entity_id: sensor.icp_identity
      from: "disconnected" 
      to: "connected"
  action:
    - service: logbook.log
      data:
        name: "ICP Identity"
        message: "ICP addon connection status changed to {{ trigger.to_state.state }}"

# Example 4: Monitor backup count changes
- alias: "ICP Identity - New backup created"
  description: "Notify when a new backup is created"
  trigger:
    - platform: state
      entity_id: sensor.icp_identity
      attribute: backup_count
  condition:
    - condition: template
      value_template: >
        {{ trigger.to_state.attributes.backup_count | int > 
           trigger.from_state.attributes.backup_count | int }}
  action:
    - service: persistent_notification.create
      data:
        title: "ICP Identity Backup"
        message: >
          New backup created! Total backups: {{ trigger.to_state.attributes.backup_count }}
        notification_id: "icp_new_backup"