homeassistant:
  name: Home
  latitude: 45.75
  longitude: 21.23
  unit_system: metric
  time_zone: Europe/Bucharest

# Essential components
frontend:
api:
websocket_api:
http:
  server_host: 0.0.0.0
  server_port: 8123

# Single consolidated ICP Identity sensor with all attributes
# Single REST sensor for ICP Identity (no separate internal sensor needed)
rest:
  - resource: "http://icp-identity:8099/stats"
    scan_interval: 30
    timeout: 10
    sensor:
      - name: "ICP Identity"
        unique_id: "icp_identity_consolidated_f8e2a9b3"
        icon: mdi:account-key
        json_attributes:
          - principal
          - public_key
          - network
          - has_mnemonic
          - identity_file
          - agent_url
          - backup_count
          - data_size_mb
        value_template: >
          {% if value_json.principal %}
            connected
          {% else %}
            disconnected
          {% endif %}

# Enable essential components for automations
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Enable shopping list (works as todo list)
shopping_list:

# Enable logging
logger:
  default: info