name: "IC Identity Manager"
version: "1.0.0"
slug: "ic-identity-manager"
description: "Internet Computer Identity Management for Home Assistant"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "IC Identity Manager API"
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)